# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('destination_name', models.CharField(max_length=200, verbose_name='جهة الإحالة')),
                ('destination_type', models.CharField(blank=True, default='', max_length=80, verbose_name='نوع الجهة')),
                ('reason', models.TextField(blank=True, default='', verbose_name='سبب الإحالة')),
                ('referral_date', models.DateTimeField(verbose_name='تاريخ الإحالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('cancelled', 'ملغاة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('followup_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات المتابعة')),
                ('qr_code_data', models.CharField(blank=True, default='', max_length=500, verbose_name='بيانات رمز QR')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='patients.patient', verbose_name='المريض')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المُحيل')),
                ('source_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='visits.visit', verbose_name='الزيارة المصدر')),
            ],
            options={
                'verbose_name': 'إحالة',
                'verbose_name_plural': 'الإحالات',
                'ordering': ['-referral_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferralFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('followup_date', models.DateTimeField(verbose_name='تاريخ المتابعة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('status', models.CharField(blank=True, default='', max_length=40, verbose_name='الحالة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_followups', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='referrals.referral', verbose_name='الإحالة')),
            ],
            options={
                'verbose_name': 'متابعة إحالة',
                'verbose_name_plural': 'متابعات الإحالات',
                'ordering': ['-followup_date'],
            },
        ),
    ]
