# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('visit_date', models.DateTimeField(verbose_name='تاريخ الزيارة')),
                ('chief_complaint', models.TextField(blank=True, default='', verbose_name='الشكوى الرئيسية')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='التشخيص')),
                ('visual_acuity_right', models.CharField(blank=True, default='', max_length=40, verbose_name='حدة الإبصار (يمين)')),
                ('visual_acuity_left', models.CharField(blank=True, default='', max_length=40, verbose_name='حدة الإبصار (يسار)')),
                ('iop_right', models.CharField(blank=True, default='', max_length=40, verbose_name='ضغط العين (يمين)')),
                ('iop_left', models.CharField(blank=True, default='', max_length=40, verbose_name='ضغط العين (يسار)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], default='open', max_length=20, verbose_name='الحالة')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_doctor_visits', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eye_organized_visits', to=settings.AUTH_USER_MODEL, verbose_name='المنظّم')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eye_visits', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'زيارة عيون',
                'verbose_name_plural': 'زيارات العيون',
                'ordering': ['-visit_date'],
            },
        ),
    ]
