# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('file_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة الملف (SHA-256)')),
                ('original_filename', models.CharField(max_length=255, verbose_name='اسم الملف الأصلي')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('import_type', models.CharField(blank=True, default='', max_length=80, verbose_name='نوع الاستيراد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('reviewing', 'قيد المراجعة'), ('completed', 'مكتملة'), ('failed', 'فاشلة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('valid_rows', models.PositiveIntegerField(default=0, verbose_name='الصفوف الصالحة')),
                ('issue_rows', models.PositiveIntegerField(default=0, verbose_name='صفوف بها مشاكل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتملت في')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='استوردها')),
            ],
            options={
                'verbose_name': 'دفعة استيراد',
                'verbose_name_plural': 'دفعات الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200, verbose_name='اسم الورقة')),
                ('sheet_index', models.PositiveIntegerField(default=0, verbose_name='ترتيب الورقة')),
                ('header_row', models.PositiveIntegerField(default=1, verbose_name='صف العناوين')),
                ('first_data_row', models.PositiveIntegerField(default=2, verbose_name='أول صف بيانات')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='إجمالي الصفوف')),
                ('actual_data_rows', models.PositiveIntegerField(default=0, verbose_name='صفوف البيانات الفعلية')),
                ('column_mapping', models.JSONField(blank=True, default=dict, verbose_name='خريطة الأعمدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='importer.importbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'ورقة استيراد',
                'verbose_name_plural': 'أوراق الاستيراد',
                'ordering': ['sheet_index'],
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0.0, verbose_name='درجة التطابق')),
                ('match_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='سبب التطابق')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_matches', to=settings.AUTH_USER_MODEL, verbose_name='راجعها')),
            ],
            options={
                'verbose_name': 'مرشّح تطابق',
                'verbose_name_plural': 'مرشّحو التطابق',
            },
        ),
        migrations.CreateModel(
            name='SourceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_row_number', models.PositiveIntegerField(verbose_name='رقم الصف الأصلي')),
                ('raw_data', models.JSONField(default=dict, verbose_name='البيانات الخام')),
                ('row_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة الصف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('reviewed', 'تمت مراجعته'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('issues_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاكل')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importbatch', verbose_name='الدفعة')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='importer.importsheet', verbose_name='الورقة')),
            ],
            options={
                'verbose_name': 'صف مصدري',
                'verbose_name_plural': 'الصفوف المصدرية',
                'ordering': ['original_row_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120, verbose_name='اسم الحقل')),
                ('original_value', models.TextField(blank=True, default='', verbose_name='القيمة الأصلية')),
                ('corrected_value', models.TextField(blank=True, default='', verbose_name='القيمة المصححة')),
                ('decision', models.CharField(choices=[('accept', 'قبول'), ('reject', 'رفض'), ('correct', 'تصحيح'), ('defer', 'تأجيل')], default='accept', max_length=20, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القرار')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to=settings.AUTH_USER_MODEL, verbose_name='قرّرها')),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='importer.sourcerow', verbose_name='الصف المصدري')),
            ],
            options={
                'verbose_name': 'قرار مراجعة',
                'verbose_name_plural': 'قرارات المراجعة',
            },
        ),
        migrations.CreateModel(
            name='MergeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('merge', 'دمج'), ('keep_separate', 'إبقاء منفصل'), ('defer', 'تأجيل')], default='defer', max_length=20, verbose_name='القرار')),
                ('decided_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ القرار')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('candidates', models.ManyToManyField(blank=True, related_name='merge_decisions', to='importer.matchcandidate', verbose_name='المرشّحون')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_decisions', to=settings.AUTH_USER_MODEL, verbose_name='قرّرها')),
                ('merged_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_decisions', to='patients.patient', verbose_name='المريض المدموج')),
            ],
            options={
                'verbose_name': 'قرار دمج',
                'verbose_name_plural': 'قرارات الدمج',
            },
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='source_row_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_a', to='importer.sourcerow', verbose_name='الصف أ'),
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='source_row_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates_b', to='importer.sourcerow', verbose_name='الصف ب'),
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_hash', models.CharField(max_length=64, verbose_name='بصمة الملف')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='importer.importbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'ملف استيراد',
                'verbose_name_plural': 'ملفات الاستيراد',
            },
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=120, verbose_name='اسم الحقل')),
                ('original_value', models.TextField(blank=True, default='', verbose_name='القيمة الأصلية')),
                ('issue_type', models.CharField(choices=[('error', 'خطأ'), ('warning', 'تحذير'), ('info', 'معلومة')], default='warning', max_length=20, verbose_name='نوع المشكلة')),
                ('severity', models.CharField(choices=[('blocking', 'مانع'), ('warning', 'تحذير'), ('info', 'معلومة')], default='warning', max_length=20, verbose_name='الخطورة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('is_auto_fixable', models.BooleanField(default=False, verbose_name='قابل للإصلاح التلقائي')),
                ('suggested_value', models.TextField(blank=True, default='', verbose_name='القيمة المقترحة')),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='importer.sourcerow', verbose_name='الصف المصدري')),
            ],
            options={
                'verbose_name': 'مشكلة بيانات',
                'verbose_name_plural': 'مشاكل البيانات',
            },
        ),
    ]
