# Generated by Django 5.2.17 on 2026-09-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
        ('patients', '0002_alter_patientcontact_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='previous_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_batches', to='importer.importbatch', verbose_name='الدفعة السابقة'),
        ),
        migrations.AddField(
            model_name='sourcerow',
            name='classification',
            field=models.CharField(choices=[('ready', 'جاهز للاستيراد'), ('review', 'يحتاج مراجعة'), ('blocking', 'خطأ مانع'), ('duplicate', 'تكرار محتمل'), ('repeat_visit', 'زيارة متكررة محتملة')], db_index=True, default='ready', max_length=20, verbose_name='التصنيف'),
        ),
        migrations.AddField(
            model_name='sourcerow',
            name='flag_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='أسباب الإشارة'),
        ),
        migrations.AddField(
            model_name='sourcerow',
            name='linked_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_rows', to='patients.patient', verbose_name='المريض المرتبط'),
        ),
        migrations.AddField(
            model_name='sourcerow',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='الاسم المطبّع'),
        ),
        migrations.AddConstraint(
            model_name='sourcerow',
            constraint=models.UniqueConstraint(fields=('batch', 'sheet', 'original_row_number'), name='uniq_source_row_location'),
        ),
    ]
