# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(default='نسخ احتياطي تلقائي', max_length=120, verbose_name='اسم الجدولة')),
                ('frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='التكرار')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='وقت التنفيذ')),
                ('destination_path', models.CharField(blank=True, default='', max_length=500, verbose_name='مسار الوجهة')),
                ('retention_count', models.PositiveIntegerField(default=7, verbose_name='عدد النسخ المحتفظ بها')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='مفعّلة')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تشغيل')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='التشغيل القادم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_schedules', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'جدولة نسخ احتياطي',
                'verbose_name_plural': 'جدولة النسخ الاحتياطي',
            },
        ),
    ]
