# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=40, unique=True, verbose_name='رقم الإصدار')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('channel', models.CharField(choices=[('stable', 'مستقر'), ('beta', 'تجريبي'), ('develop', 'تطوير')], default='stable', max_length=20, verbose_name='القناة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الإصدار')),
                ('is_current', models.BooleanField(default=False, verbose_name='الإصدار الحالي')),
                ('db_schema_version', models.CharField(default='1', max_length=40, verbose_name='إصدار مخطط قاعدة البيانات')),
            ],
            options={
                'verbose_name': 'إصدار التطبيق',
                'verbose_name_plural': 'إصدارات التطبيق',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('name', models.CharField(max_length=120, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='الرمز')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التفعيل')),
                ('trial_days', models.PositiveIntegerField(default=30, verbose_name='أيام التجربة')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_trial', models.BooleanField(default=True, verbose_name='نسخة تجريبية')),
                ('is_expired', models.BooleanField(default=False, verbose_name='منتهية')),
                ('license_key', models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح الترخيص (مجزّأ)')),
                ('mode', models.CharField(choices=[('trial', 'تجربة'), ('licensed', 'مرخّص'), ('read_only', 'قراءة فقط')], default='trial', max_length=20, verbose_name='الوضع')),
                ('last_verified', models.DateTimeField(blank=True, null=True, verbose_name='آخر تحقق')),
            ],
            options={
                'verbose_name': 'حالة الترخيص',
                'verbose_name_plural': 'حالة الترخيص',
            },
        ),
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.PositiveIntegerField(default=8765, verbose_name='المنفذ')),
                ('allow_network_access', models.BooleanField(default=False, verbose_name='السماح بالوصول عبر الشبكة')),
                ('bind_address', models.CharField(default='127.0.0.1', max_length=40, verbose_name='عنوان الربط')),
                ('max_connections', models.PositiveIntegerField(default=50, verbose_name='أقصى عدد اتصالات')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الخادم',
                'verbose_name_plural': 'إعدادات الخادم',
            },
        ),
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_version', models.CharField(max_length=40, verbose_name='من إصدار')),
                ('to_version', models.CharField(max_length=40, verbose_name='إلى إصدار')),
                ('update_type', models.CharField(choices=[('optional', 'اختياري'), ('recommended', 'موصى به'), ('security', 'أمني')], default='optional', max_length=20, verbose_name='نوع التحديث')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('failed', 'فشل'), ('rolled_back', 'تم التراجع')], default='pending', max_length=20, verbose_name='الحالة')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='اكتمل في')),
                ('rollback_available', models.BooleanField(default=False, verbose_name='التراجع متاح')),
                ('backup_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف النسخة الاحتياطية')),
            ],
            options={
                'verbose_name': 'سجل تحديث',
                'verbose_name_plural': 'سجل التحديثات',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(default='manual', max_length=40, verbose_name='نوع النسخة')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف')),
                ('checksum', models.CharField(blank=True, default='', max_length=128, verbose_name='البصمة (checksum)')),
                ('db_version', models.CharField(blank=True, default='', max_length=40, verbose_name='إصدار قاعدة البيانات')),
                ('app_version', models.CharField(blank=True, default='', max_length=40, verbose_name='إصدار التطبيق')),
                ('status', models.CharField(choices=[('success', 'ناجح'), ('failed', 'فاشل'), ('in_progress', 'قيد التنفيذ')], default='in_progress', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'سجل النسخ الاحتياطي',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('login_failed', 'محاولة دخول فاشلة'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد'), ('other', 'أخرى')], max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(blank=True, default='', max_length=100, verbose_name='النموذج')),
                ('object_id', models.CharField(blank=True, default='', max_length=100, verbose_name='معرّف السجل')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='وصف السجل')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=255, verbose_name='وكيل المتصفح')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التوقيت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-timestamp'],
            },
        ),
    ]
