# Generated by Django 5.2.17 on 2026-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('clinic', 'عيادة'), ('laboratory', 'مختبر'), ('diagnostic', 'خدمة تشخيصية'), ('administration', 'إدارة')], default='clinic', max_length=20, verbose_name='نوع القسم'),
        ),
    ]
