# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='المعرّف')),
                ('internal_code', models.CharField(max_length=40, unique=True, verbose_name='الرمز الداخلي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('unknown', 'غير محدد')], default='unknown', max_length=10, verbose_name='الجنس')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('approx_age_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='العمر التقريبي')),
                ('approx_age_unit', models.CharField(blank=True, choices=[('year', 'سنة'), ('month', 'شهر'), ('day', 'يوم')], default='', max_length=10, verbose_name='وحدة العمر')),
                ('approx_age_recorded_date', models.DateField(blank=True, null=True, verbose_name='تاريخ تسجيل العمر التقريبي')),
                ('is_approx_age', models.BooleanField(default=False, verbose_name='عمر تقريبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='أنشأه')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('is_primary', models.BooleanField(default=False, verbose_name='أساسي')),
                ('source', models.CharField(blank=True, default='', max_length=80, verbose_name='المصدر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'اسم مريض',
                'verbose_name_plural': 'أسماء المرضى',
                'ordering': ['-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('contact_type', models.CharField(choices=[('phone', 'هاتف'), ('mobile', 'جوال'), ('email', 'بريد إلكتروني')], default='mobile', max_length=20, verbose_name='النوع')),
                ('value', models.CharField(max_length=120, verbose_name='القيمة')),
                ('is_primary', models.BooleanField(default=False, verbose_name='أساسي')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'وسيلة تواصل',
                'verbose_name_plural': 'وسائل التواصل',
            },
        ),
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('address_type', models.CharField(blank=True, default='', max_length=40, verbose_name='نوع العنوان')),
                ('text', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('city', models.CharField(blank=True, default='', max_length=80, verbose_name='المدينة')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'عنوان',
                'verbose_name_plural': 'العناوين',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for', to='patients.patientname', verbose_name='الاسم الأساسي'),
        ),
    ]
