# Generated by Django 5.2.17 on 2026-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcontact',
            name='value',
            field=models.CharField(db_index=True, max_length=120, verbose_name='القيمة'),
        ),
        migrations.AlterField(
            model_name='patientname',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='الاسم الكامل'),
        ),
    ]
