# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, verbose_name='الإصدار')),
                ('channel', models.CharField(choices=[('stable', 'مستقر'), ('beta', 'تجريبي'), ('develop', 'تطوير')], default='stable', max_length=20, verbose_name='القناة')),
                ('update_type', models.CharField(choices=[('optional', 'اختياري'), ('recommended', 'موصى به'), ('security', 'أمني')], default='optional', max_length=20, verbose_name='نوع التحديث')),
                ('download_url', models.URLField(blank=True, default='', verbose_name='رابط التنزيل')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='بصمة SHA-256')),
                ('min_supported_version', models.CharField(blank=True, default='', max_length=40, verbose_name='أدنى إصدار مدعوم')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('message_ar', models.TextField(blank=True, default='', verbose_name='الرسالة (عربي)')),
                ('is_mandatory', models.BooleanField(default=False, verbose_name='إلزامي')),
                ('allow_postpone', models.BooleanField(default=True, verbose_name='السماح بالتأجيل')),
                ('grace_period_days', models.PositiveIntegerField(default=0, verbose_name='فترة السماح (أيام)')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الفحص')),
            ],
            options={
                'verbose_name': 'بيان تحديث',
                'verbose_name_plural': 'بيانات التحديث',
                'ordering': ['-checked_at'],
            },
        ),
    ]
