# Generated by Django 4.2.30 on 2026-09-15 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('visit_date', models.DateTimeField(verbose_name='تاريخ الزيارة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة'), ('cancelled', 'ملغاة')], default='open', max_length=20, verbose_name='الحالة')),
                ('chief_complaint', models.TextField(blank=True, default='', verbose_name='الشكوى الرئيسية')),
                ('diagnosis', models.TextField(blank=True, default='', verbose_name='التشخيص')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.department', verbose_name='القسم')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL, verbose_name='الطبيب')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_visits', to=settings.AUTH_USER_MODEL, verbose_name='المنظّم')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'زيارة',
                'verbose_name_plural': 'الزيارات',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('service_code', models.CharField(blank=True, default='', max_length=40, verbose_name='رمز الخدمة')),
                ('service_name', models.CharField(max_length=200, verbose_name='اسم الخدمة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('notes', models.CharField(blank=True, default='', max_length=255, verbose_name='ملاحظات')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='visits.visit', verbose_name='الزيارة')),
            ],
            options={
                'verbose_name': 'خدمة زيارة',
                'verbose_name_plural': 'خدمات الزيارات',
            },
        ),
    ]
